### ISSUE TITLE
Start GSC Problem | AtianMenu 

### ISSUE THREAD

**Issue by shadowrun321** [shiversoftdev/t7-compiler#12]
when I try to run GSC injector, show me ERROR : 

Checking client version... (our version is 3000000060006)
224,0987 ms compile time (excluding irony)
 -- 202,0993 ms to build the structure.
 -- 21,9994 ms to commit to binary

The index was outside the bounds of the array....

........................................................
How fix it!? Thx!

**Comment by shiversoftdev** [comment]
fixed, sorry.

**Comment by shadowrun321** [comment]
Thank You! :) Soooo Muchhhh!
