### ISSUE TITLE
Client Version Update Loop, Broken (Non functional program)

### ISSUE THREAD

**Issue by HOONIG4N** [shiversoftdev/t7-compiler#14]
The application has been functioning fine for a very long time and has a had a lot of use by myself and others, suddenly a new update arises and I am no longer able to use the program, every time I open the program it proceeds to say there is a newer version available, it then pretends to download the new version and prompts me with a window saying:
 "Compiler Updated! 
Your t7 compiler installation was just updated. You may proceed with your compilation action" 

I press accept and the window crashes, I then reopen it through various means and it presents me with the same fault on loop, update required, updated downloaded, CRASH.. and this has been going on for the last 3 days and I feel you may not be aware of the problem but now both me and my friends are unable to utilise your facilities, please make yourselves aware of this issue as it has completely broken everything you have worked for, we cannot use it anymore due to this.

If you require further details please reach out, this isn't just a problem on my end.  This problem exists with all of my associates.

**Comment by shiversoftdev** [comment]
Whatever program you are using is the issue, not the compiler. "Your t7 compiler installation was just updated. You may proceed with your compilation action" does not exist as a string in my entire codebase. You are using third party software that has not correctly handled updates. Report it to that developer.
