### ISSUE TITLE
 the update broke BO4 Injection

### ISSUE THREAD

**Issue by NemoHaze1137** [shiversoftdev/t7-compiler#3]
I got that error
s_assetPool:ScriptParseTree => 00007FF6C29FBBB0
Unable to identify critical injection information. Double check your script path, and try restarting the game. Make sure you are injecting in the pregame lobby.

[scripts/zm_common/load.gsc]: Failed to Inject (0000000000000001)

**Comment by TheUnknownCod3r** [comment]
Just closed my issue, as you opened this one. Compilation works, Injection fails. Can confirm
